---
functional:
  - Люди во время решения задачи должны видеть написание кода друг друга
  - У пользователя должна быть возможность соревноваться как с ботом, так и с реальными людьми
  - У пользователя должна быть возможность создавать игры по своему желанию из предложенных критериев (уровень сложности, время, бот или еальный человек, сфера задания или само задание)
  - У пользователя должна быть возможность просматривать свою статистику в профиле
  - У пользователя должна быть возможность выбирать любой из предложенных языков программирования во время игры
  - У пользователя должна быть возможность видеть предложенное задание во время игры 
  - У пользователя должна быть возможность переводить задание с английского языка на русский и наоборот
  - У пользователя должна быть возможность сбросить код до изначально заданного
  - У пользователя должна быть возможность проверить код на правильность
  - У пользователя должна быть возможность сдаться 
  - У пользователя должна быть возможность общаться с соперником в чате
  - У пользователя должна быть возможность общаться с другими людьми в чате приложения на главной странице
non-functional:
  - Cайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - 
